### ISSUE TITLE
Problem with postgreSQL on method NodeResource.findAll

### ISSUE THREAD

**Issue by nicolas59** [ligoj/ligoj-api#4]
On postgres, error occured when we try to access to the subscription page

2017-09-14 11:40:17.066 ERROR ERREUR: la fonction upper(bytea) n'existe pas
  Indice : Aucune fonction ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.

Query ; 
select node0_.id as id1_8_, node0_.name as name2_8_, node0_.mode as mode3_8_, node0_.refined as refined7_8_, node0_.tag as tag4_8_, node0_.tag_ui_classes as tag_ui_c5_8_, node0_.ui_classes as ui_class6_8_ from ligoj_node node0_ left outer join ligoj_node node1_ on node0_.refined=node1_.id left outer join ligoj_node node2_ on node1_.refined=node2_.id where (? is null or ?='service' and (node0_.refined is null) or node0_.refined=?) and (?<0 or ?>1 or ?=0 and (node1_.id is null) or ?=1 and (node2_.id is null)) and (? is null or node0_.mode=? or node0_.mode='ALL') and (? is null or upper(node0_.name) like upper((('%'||?)||'%'))) and (exists (select 1 from s_role_assignment systemrole3_ inner join s_role systemrole4_ on systemrole3_.role=systemrole4_.id where systemrole3_."user"=? and (exists (select 1 from s_authorization systemauth5_ where systemauth5_.role=systemrole4_.id and systemauth5_.pattern='.*' and systemauth5_.type='API'))) or exists (select 1 from ligoj_delegate_node delegateno6_ where (node0_.id like (delegateno6_.name||':%') or delegateno6_.name=node0_.id) and (delegateno6_.receiver_type='USER' and delegateno6_.receiver=? or delegateno6_.receiver_type='GROUP' and (exists (select 1 from ligoj_cache_group cachegroup7_ where receiver=cachegroup7_.id and (exists (select 1 from ligoj_cache_membership cachemembe8_ inner join ligoj_cache_group cachegroup9_ on cachemembe8_."group"=cachegroup9_.id where cachemembe8_."user"=? and (cachegroup9_.description=cachegroup7_.description or cachegroup9_.description like ('%,'||cachegroup7_.description)))))) or delegateno6_.receiver_type='COMPANY' and (exists (select 1 from ligoj_cache_company cachecompa10_ where receiver=cachecompa10_.id and (exists (select 1 from ligoj_cache_user cacheuser11_ inner join ligoj_cache_company cachecompa12_ on cacheuser11_.company=cachecompa12_.id where cacheuser11_.id=? and (cachecompa12_.description=cachecompa10_.description or cachecompa12_.description like ('%,'||cachecompa10_.description))))))))) order by node0_.id limit ?

**Comment by fabdouglas** [comment]
In fact, the function exists, but postgresql cannot handle ".... UPPER(:param)" when ":param" is null. When it parses the full SQL query to determine the type, it resolves the ":param" to NULL and uses "byte" as default type. 
The fix is ensuring this string is never NULL in the prepare statement.
